apiVersion: argoproj.io/v1alpha1
kind: Application  # 각종 환경 설정 적용
metadata:
  name: raillo-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/goorm-sudo/raillo-backend
    targetRevision: main
    path: k8s # Argo CD는 내부적으로 Git repo를 clone 한 뒤 path에 지정된 상대 경로에서 YAML 파일을 찾기 때문에 /를 빼야함
  destination:
    # https://kubernetes.default.svc: Argo CD 자체가 설치된 클러스터의 내부 주소
    server: https://kubernetes.default.svc
    namespace: raillo    # 한 개의 Application 당 한 개의 namespace 담당
  syncPolicy:
    # Argo CD가 개발자가 직접 명령하지 않아도 자동으로 GitHub에 있는 매니페스트를 클러스터에 적용
    automated:
      # GitHub에서 삭제된 리소스는 클러스터에서도 자동 삭제
      prune: true
      # 클러스터 안에서 수동으로 리소스가 변경되면, GitHub에 있는 원래 상태로 자동 복구
      selfHeal: true
